window.moonWorldPacks=[
{
name:'Abyssal Archive',currency:'Pearls',currencyLabel:'pearls',prestige:'Tideglass',clicker:'🫧',scene:'The deep remembers',theme:'ocean',trees:[['seed','🪸'],['pear','🐚'],['bees','🪼'],['comet','🐠']],
items:[
{id:'seed',name:'Coral Sprout',icon:'🪸',base:15,power:.4,kind:'grow',desc:'A tiny reef gathers a little pearl dust.'},
{id:'pear',name:'Pearl Clam',icon:'🐚',base:70,power:1.8,kind:'grow',desc:'Grows lustrous pearls in the quiet.'},
{id:'mist',name:'Kelp Current',icon:'🌿',base:190,power:5,kind:'grow',desc:'A steady current feeds the reef.'},
{id:'bees',name:'Jellyfish Garden',icon:'🪼',base:520,power:16,kind:'grow',desc:'Drifting jellies gather ocean-glow.'},
{id:'house',name:'Glass Submarine',icon:'🤿',base:1700,power:52,kind:'grow',desc:'A bright habitat for deep-sea growth.'},
{id:'comet',name:'Anglerfish Grove',icon:'🐠',base:5800,power:175,kind:'grow',desc:'Beacon lights draw in rare pearls.'},
{id:'press',name:'Tidal Pearl Press',icon:'⚙️',base:19000,power:580,kind:'grow',desc:'Turns tidal pressure into treasure.'},
{id:'nebula',name:'Abyssal Reef',icon:'🌊',base:76000,power:2050,kind:'grow',desc:'A vast reef blooms far below.'},
{id:'firefly',name:'Cleaner Shrimp',icon:'🦐',base:25,auto:.9,kind:'auto',desc:'A tiny helper clicks the shell for you.'},
{id:'robot',name:'Bubble Bot',icon:'🤖',base:320,auto:7,kind:'auto',desc:'A tireless bot taps out a pearl rhythm.'},
{id:'drone',name:'Manta Ray Fleet',icon:'🛸',base:3000,auto:42,kind:'auto',desc:'A gliding fleet harvests automatically.'},
{id:'gloves',name:'Diver Mitts',icon:'🧤',base:45,tap:2,kind:'click',desc:'Grip the shell for a stronger click.'},
{id:'boots',name:'Trench Stompers',icon:'🥾',base:340,tap:7,kind:'click',desc:'Send a satisfying ripple through the deep.'},
{id:'wand',name:'Tidecaller Trident',icon:'🔱',base:2600,tap:32,kind:'click',desc:'Command the current with every tap.'},
{id:'gauntlet',name:'Leviathan Grip',icon:'🐙',base:22000,tap:150,kind:'click',desc:'The deep answers with a giant harvest.'},
{id:'lens',name:'Biolume Lens',icon:'🔮',base:9500,boost:.05,kind:'boost',desc:'Boosts all pearl production by 5%.'},
{id:'starcore',name:'Thermal Vent',icon:'🌋',base:150000,power:5600,kind:'grow',desc:'A warm vent fuels a bustling garden.'},
{id:'astrolabe',name:'Current Cartographer',icon:'🧭',base:440000,power:18000,kind:'grow',desc:'Maps the richest paths through the sea.'},
{id:'moonengine',name:'Abyssal Engine',icon:'⚓',base:1600000,power:61000,kind:'grow',desc:'Harnesses the pressure of the trench.'},
{id:'galaxyfarm',name:'Continental Reef',icon:'🪸',base:9000000,power:250000,kind:'grow',desc:'A reef stretches across the ocean floor.'},
{id:'cosmicseed',name:'Worldshell Nursery',icon:'🥚',base:52000000,power:1000000,kind:'grow',desc:'A new ocean world grows inside.'},
{id:'constellation',name:'Bubble Constellation',icon:'✨',base:135000,power:0,auto:115,kind:'auto',desc:'A starry chain of automated shell taps.'},
{id:'orbitalswarm',name:'Pearl Diver Fleet',icon:'🚤',base:820000,power:0,auto:680,kind:'auto',desc:'A fleet works every reef in the archive.'},
{id:'eclipsehammer',name:'Tsunami Mallet',icon:'🔨',base:135000,tap:700,kind:'click',desc:'Make a wave that shakes pearls loose.'},
{id:'quasarknuckles',name:'Kraken Claws',icon:'🦑',base:980000,tap:3400,kind:'click',desc:'Unleash the power of the abyss.'},
{id:'abyssheart',name:'Abyss Heart',icon:'💙',base:3200000,power:10500,kind:'grow',desc:'A living heart powers the deepest gardens.'},
{id:'leviathan',name:'Leviathan Nursery',icon:'🐋',base:14000000,power:68000,kind:'grow',desc:'A gentle giant cultivates a whole sea.'},
{id:'trenchrelay',name:'Trench Relay',icon:'📡',base:2300000,auto:1650,kind:'auto',desc:'Signals make the whole deep click in rhythm.'},
{id:'tidalcrown',name:'Tidal Crown',icon:'👑',base:6200000,boost:.1,kind:'boost',desc:'Raises all pearl production by 10%.'},
{id:'krakenclaw',name:'Kraken Claw',icon:'🦾',base:18000000,tap:21000,kind:'click',desc:'A single click shakes the ocean floor.'}
],
areas:[{name:'Sunlit Shoal',sub:'A bright reef just beneath the waves · +0% garden production.',icon:'🐚',cost:0,multiplier:1},{name:'Kelp Cathedral',sub:'Towering kelp sways with rich currents · +15% garden production.',icon:'🌿',cost:5000,multiplier:1.15},{name:'The Blue Trench',sub:'Rare pearls glimmer in the dark · +35% garden production.',icon:'🌊',cost:80000,multiplier:1.35},{name:'Thermal Gardens',sub:'Warm vents keep every coral thriving · +60% garden production.',icon:'🌋',cost:1000000,multiplier:1.6},{name:'The Lost Continent',sub:'A whole hidden world blooms below · +100% garden production.',icon:'🏝️',cost:25000000,multiplier:2}],
paths:[['northstar','Tide Compass','Pearl clicks gain +15% power per rank.'],['orchard','Reef Crown','All production gains +10% per rank.'],['wayfinder','Current Guide','Active reef bonuses grow +15% stronger per rank.']]
},
{
name:'Clockwork Wilds',currency:'Gears',currencyLabel:'gears',prestige:'Time Cores',clicker:'⚙️',scene:'The forest runs on wonder',theme:'forest',trees:[['seed','🌱'],['pear','🌳'],['bees','🍄'],['comet','🌲']],
items:[
{id:'seed',name:'Brass Acorn',icon:'🌰',base:15,power:.4,kind:'grow',desc:'A little acorn winds up your harvest.'},
{id:'pear',name:'Copperwood Tree',icon:'🌳',base:70,power:1.8,kind:'grow',desc:'Leaves catch and store forest energy.'},
{id:'mist',name:'Spring Rain',icon:'🌧️',base:190,power:5,kind:'grow',desc:'A gentle shower keeps the gears turning.'},
{id:'bees',name:'Clockwork Fungi',icon:'🍄',base:520,power:16,kind:'grow',desc:'Spore rings spread through the woodland.'},
{id:'house',name:'Cuckoo Lodge',icon:'🏡',base:1700,power:52,kind:'grow',desc:'A cozy home for your mechanical helpers.'},
{id:'comet',name:'Pendulum Pine',icon:'🌲',base:5800,power:175,kind:'grow',desc:'Its branches swing with every passing hour.'},
{id:'press',name:'Gearworks Mill',icon:'⚙️',base:19000,power:580,kind:'grow',desc:'Wind and water become forest gears.'},
{id:'nebula',name:'Everclock Grove',icon:'🌳',base:76000,power:2050,kind:'grow',desc:'A woodland that never stops growing.'},
{id:'firefly',name:'Ticking Firefly',icon:'✨',base:25,auto:.9,kind:'auto',desc:'A tiny light clicks the acorn for you.'},
{id:'robot',name:'Woodland Automaton',icon:'🤖',base:320,auto:7,kind:'auto',desc:'A friendly helper keeps perfect time.'},
{id:'drone',name:'Clockwork Owl',icon:'🦉',base:3000,auto:42,kind:'auto',desc:'An owl patrols and taps through the night.'},
{id:'gloves',name:'Tinker Gloves',icon:'🧤',base:45,tap:2,kind:'click',desc:'A careful grip winds a stronger click.'},
{id:'boots',name:'Springheel Boots',icon:'🥾',base:340,tap:7,kind:'click',desc:'Bounce through the forest with a mighty tap.'},
{id:'wand',name:'Hourglass Wand',icon:'⌛',base:2600,tap:32,kind:'click',desc:'Bend a moment into a larger harvest.'},
{id:'gauntlet',name:'Ironwood Gauntlet',icon:'🦾',base:22000,tap:150,kind:'click',desc:'A powerful click shakes the whole grove.'},
{id:'lens',name:'Chrono Crystal',icon:'🔮',base:9500,boost:.05,kind:'boost',desc:'Boosts all gear production by 5%.'},
{id:'starcore',name:'Heartwood Furnace',icon:'🔥',base:150000,power:5600,kind:'grow',desc:'A warm heart keeps the wilds thriving.'},
{id:'astrolabe',name:'Grand Orrery',icon:'🪐',base:440000,power:18000,kind:'grow',desc:'Planets mark the richest growing seasons.'},
{id:'moonengine',name:'Timekeeper Engine',icon:'⏱️',base:1600000,power:61000,kind:'grow',desc:'Turns every passing second into gears.'},
{id:'galaxyfarm',name:'Infinite Canopy',icon:'🌌',base:9000000,power:250000,kind:'grow',desc:'A canopy stretches across every timeline.'},
{id:'cosmicseed',name:'First World Acorn',icon:'🌍',base:52000000,power:1000000,kind:'grow',desc:'A whole new world begins to grow.'},
{id:'constellation',name:'Owl Clock Circle',icon:'🦉',base:135000,power:0,auto:115,kind:'auto',desc:'A ring of owls taps in sync.'},
{id:'orbitalswarm',name:'Tinker Sprite Swarm',icon:'🧚',base:820000,power:0,auto:680,kind:'auto',desc:'Sprites keep every grove in motion.'},
{id:'eclipsehammer',name:'Thunder Mallet',icon:'🔨',base:135000,tap:700,kind:'click',desc:'One strike sends gears spinning.'},
{id:'quasarknuckles',name:'Timequake Fist',icon:'👊',base:980000,tap:3400,kind:'click',desc:'Punch a hole through the slow moments.'},
{id:'worldroot',name:'Worldroot Dynamo',icon:'🌱',base:3200000,power:10500,kind:'grow',desc:'Roots draw energy from every age.'},
{id:'everclock',name:'Everclock Tower',icon:'🕰️',base:14000000,power:68000,kind:'grow',desc:'A whole timeline grows around its gears.'},
{id:'spriteRelay',name:'Sprite Relay',icon:'📡',base:2300000,auto:1650,kind:'auto',desc:'Sprites share a perfect clicking rhythm.'},
{id:'seasonCrown',name:'Season Crown',icon:'👑',base:6200000,boost:.1,kind:'boost',desc:'Raises all gear production by 10%.'},
{id:'timequakeClaw',name:'Timequake Claw',icon:'🦾',base:18000000,tap:21000,kind:'click',desc:'One tap rattles the whole timeline.'}
],
areas:[{name:'Brassleaf Clearing',sub:'A warm place to wind up · +0% garden production.',icon:'🌰',cost:0,multiplier:1},{name:'Mushroom Clockwalk',sub:'Fungi glow in time with the gears · +15% garden production.',icon:'🍄',cost:5000,multiplier:1.15},{name:'Pendulum Pines',sub:'Every bough keeps perfect time · +35% garden production.',icon:'🌲',cost:80000,multiplier:1.35},{name:'The Tinker’s Hollow',sub:'Little workshops hum beneath the roots · +60% garden production.',icon:'🛠️',cost:1000000,multiplier:1.6},{name:'The Everclock',sub:'The forest grows through every age · +100% garden production.',icon:'⏳',cost:25000000,multiplier:2}],
paths:[['northstar','Clockhand','Clicks gain +15% power per rank.'],['orchard','Heartwood Crown','All production gains +10% per rank.'],['wayfinder','Timekeeper','Garden bonuses grow +15% stronger per rank.']]
}];
